real_data: /home/annabelzhu/Repositories/stdg-eval/examples/data/real.csv
synthetic_datasets:
- name: synth1
  path: /home/annabelzhu/Repositories/stdg-eval/examples/data/synth1.csv
- name: synth2
  path: /home/annabelzhu/Repositories/stdg-eval/examples/data/synth2.csv
column_types:
  age: numerical
  bmi: numerical
  sbp: numerical
  sex: categorical
  diagnosis: categorical
  smoker: categorical
metrics:
  # Univariate
  wasserstein: false
  tvd: false
  hellinger: true
  # Bivariate
  spearman: true
  contingency: true
  # Multivariate
  cross_classification: true
  propensity_mse: true
  # Missingness
  rate: true
  set_distribution: true
  classifier_auroc: true
  dependency_structure: true
